apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil-app-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /app
        backend:
          service:
            name: wil-app-service
            port:
              number: 81
